[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "18"

# Configurações das variáveis de ambiente para produção
[context.production.environment]
  VITE_SUPABASE_URL = "https://uxbeaslwirkepnowydfu.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4YmVhc2x3aXJrZXBub3d5ZGZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MTQwNTUsImV4cCI6MjA1NzM5MDA1NX0.bhPFhXaCgp363YlcAWtNhPlpj82dSNUWwNim2fgYh5s"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configurações de segurança para HTTPS
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "upgrade-insecure-requests"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
