// src/components/UserProfile/company/CountryStates.ts

// Estados do Brasil
const brazilStates = [
  { value: "AC", label: "Acre" },
  { value: "AL", label: "Alagoas" },
  { value: "AP", label: "Amapá" },
  { value: "AM", label: "Amazonas" },
  { value: "BA", label: "Bahia" },
  { value: "CE", label: "Ceará" },
  { value: "DF", label: "Distrito Federal" },
  { value: "ES", label: "Espírito Santo" },
  { value: "GO", label: "Goiás" },
  { value: "MA", label: "Maranhão" },
  { value: "MT", label: "Mato Grosso" },
  { value: "MS", label: "Mato Grosso do Sul" },
  { value: "MG", label: "Minas Gerais" },
  { value: "PA", label: "Pará" },
  { value: "PB", label: "Paraíba" },
  { value: "PR", label: "Paraná" },
  { value: "PE", label: "Pernambuco" },
  { value: "PI", label: "Piauí" },
  { value: "RJ", label: "Rio de Janeiro" },
  { value: "RN", label: "Rio Grande do Norte" },
  { value: "RS", label: "Rio Grande do Sul" },
  { value: "RO", label: "Rondônia" },
  { value: "RR", label: "Roraima" },
  { value: "SC", label: "Santa Catarina" },
  { value: "SP", label: "São Paulo" },
  { value: "SE", label: "Sergipe" },
  { value: "TO", label: "Tocantins" }
];

// Exemplo para Estados Unidos
const usStates = [
  { value: "AL", label: "Alabama" },
  { value: "AK", label: "Alaska" },
  { value: "AZ", label: "Arizona" },
  { value: "AR", label: "Arkansas" },
  { value: "CA", label: "California" },
  { value: "CO", label: "Colorado" },
  { value: "CT", label: "Connecticut" },
  { value: "DE", label: "Delaware" },
  { value: "FL", label: "Florida" },
  { value: "GA", label: "Georgia" },
  { value: "HI", label: "Hawaii" },
  { value: "ID", label: "Idaho" },
  { value: "IL", label: "Illinois" },
  { value: "IN", label: "Indiana" },
  { value: "IA", label: "Iowa" },
  { value: "KS", label: "Kansas" },
  { value: "KY", label: "Kentucky" },
  { value: "LA", label: "Louisiana" },
  { value: "ME", label: "Maine" },
  { value: "MD", label: "Maryland" },
  { value: "MA", label: "Massachusetts" },
  { value: "MI", label: "Michigan" },
  { value: "MN", label: "Minnesota" },
  { value: "MS", label: "Mississippi" },
  { value: "MO", label: "Missouri" },
  { value: "MT", label: "Montana" },
  { value: "NE", label: "Nebraska" },
  { value: "NV", label: "Nevada" },
  { value: "NH", label: "New Hampshire" },
  { value: "NJ", label: "New Jersey" },
  { value: "NM", label: "New Mexico" },
  { value: "NY", label: "New York" },
  { value: "NC", label: "North Carolina" },
  { value: "ND", label: "North Dakota" },
  { value: "OH", label: "Ohio" },
  { value: "OK", label: "Oklahoma" },
  { value: "OR", label: "Oregon" },
  { value: "PA", label: "Pennsylvania" },
  { value: "RI", label: "Rhode Island" },
  { value: "SC", label: "South Carolina" },
  { value: "SD", label: "South Dakota" },
  { value: "TN", label: "Tennessee" },
  { value: "TX", label: "Texas" },
  { value: "UT", label: "Utah" },
  { value: "VT", label: "Vermont" },
  { value: "VA", label: "Virginia" },
  { value: "WA", label: "Washington" },
  { value: "WV", label: "West Virginia" },
  { value: "WI", label: "Wisconsin" },
  { value: "WY", label: "Wyoming" }
];

// Exemplo para Argentina
const arStates = [
  { value: "B", label: "Buenos Aires" },
  { value: "C", label: "Ciudad Autónoma de Buenos Aires" },
  { value: "K", label: "Catamarca" },
  { value: "H", label: "Chaco" },
  { value: "U", label: "Chubut" },
  { value: "X", label: "Córdoba" },
  { value: "W", label: "Corrientes" },
  { value: "E", label: "Entre Ríos" },
  { value: "P", label: "Formosa" },
  { value: "Y", label: "Jujuy" },
  { value: "L", label: "La Pampa" },
  { value: "F", label: "La Rioja" },
  { value: "M", label: "Mendoza" },
  { value: "N", label: "Misiones" },
  { value: "Q", label: "Neuquén" },
  { value: "R", label: "Río Negro" },
  { value: "A", label: "Salta" },
  { value: "J", label: "San Juan" },
  { value: "D", label: "San Luis" },
  { value: "Z", label: "Santa Cruz" },
  { value: "S", label: "Santa Fe" },
  { value: "G", label: "Santiago del Estero" },
  { value: "V", label: "Tierra del Fuego" },
  { value: "T", label: "Tucumán" }
];

// Estados da Bolívia
const boStates = [
  { value: "L", label: "La Paz" },
  { value: "C", label: "Cochabamba" },
  { value: "S", label: "Santa Cruz" },
  { value: "P", label: "Potosí" },
  { value: "O", label: "Oruro" },
  { value: "T", label: "Tarija" },
  { value: "H", label: "Chuquisaca" },
  { value: "N", label: "Pando" }
];

// Regiões do Chile
const clStates = [
  { value: "XV", label: "Región de Arica y Parinacota" },
  { value: "I", label: "Región de Tarapacá" },
  { value: "II", label: "Región de Antofagasta" },
  { value: "III", label: "Región de Atacama" },
  { value: "IV", label: "Región de Coquimbo" },
  { value: "V", label: "Región de Valparaíso" },
  { value: "RM", label: "Región Metropolitana de Santiago" },
  { value: "VI", label: "Región del Libertador General Bernardo O'Higgins" },
  { value: "VII", label: "Región del Maule" },
  { value: "XVI", label: "Región de Ñuble" },
  { value: "VIII", label: "Región del Biobío" },
  { value: "IX", label: "Región de la Araucanía" },
  { value: "XIV", label: "Región de Los Ríos" },
  { value: "X", label: "Región de Los Lagos" },
  { value: "XI", label: "Región Aysén del General Carlos Ibáñez del Campo" },
  { value: "XII", label: "Región de Magallanes y de la Antártica Chilena" }
];

// Departamentos da Colômbia
const coStates = [
  { value: "DC", label: "Bogotá D.C." },
  { value: "AMA", label: "Amazonas" },
  { value: "ANT", label: "Antioquia" },
  { value: "ARA", label: "Arauca" },
  { value: "ATL", label: "Atlántico" },
  { value: "BOL", label: "Bolívar" },
  { value: "BOY", label: "Boyacá" },
  { value: "CAL", label: "Caldas" },
  { value: "CAQ", label: "Caquetá" },
  { value: "CAS", label: "Casanare" },
  { value: "CAU", label: "Cauca" },
  { value: "CES", label: "Cesar" },
  { value: "CHO", label: "Chocó" },
  { value: "COR", label: "Córdoba" },
  { value: "CUN", label: "Cundinamarca" },
  { value: "GUA", label: "Guainía" },
  { value: "GUV", label: "Guaviare" },
  { value: "HUI", label: "Huila" },
  { value: "LAG", label: "La Guajira" },
  { value: "MAG", label: "Magdalena" },
  { value: "MET", label: "Meta" },
  { value: "NAR", label: "Nariño" },
  { value: "NSA", label: "Norte de Santander" },
  { value: "PUT", label: "Putumayo" },
  { value: "QUI", label: "Quindío" },
  { value: "RIS", label: "Risaralda" },
  { value: "SAN", label: "Santander" },
  { value: "SUC", label: "Sucre" },
  { value: "TOL", label: "Tolima" },
  { value: "VAC", label: "Valle del Cauca" },
  { value: "VAU", label: "Vaupés" },
  { value: "VID", label: "Vichada" }
];

// Províncias do Equador
const ecStates = [
  { value: "A", label: "Azuay" },
  { value: "B", label: "Bolívar" },
  { value: "F", label: "Cañar" },
  { value: "C", label: "Carchi" },
  { value: "H", label: "Chimborazo" },
  { value: "X", label: "Cotopaxi" },
  { value: "O", label: "El Oro" },
  { value: "E", label: "Esmeraldas" },
  { value: "W", label: "Galápagos" },
  { value: "G", label: "Guayas" },
  { value: "I", label: "Imbabura" },
  { value: "L", label: "Loja" },
  { value: "R", label: "Los Ríos" },
  { value: "M", label: "Manabí" },
  { value: "S", label: "Morona-Santiago" },
  { value: "N", label: "Napo" },
  { value: "D", label: "Orellana" },
  { value: "Y", label: "Pastaza" },
  { value: "P", label: "Pichincha" },
  { value: "SE", label: "Santa Elena" },
  { value: "SD", label: "Santo Domingo de los Tsáchilas" },
  { value: "U", label: "Sucumbíos" },
  { value: "T", label: "Tungurahua" },
  { value: "Z", label: "Zamora-Chinchipe" }
];

// Regiões da Guiana
const gyStates = [
  { value: "BA", label: "Barima-Waini" },
  { value: "CU", label: "Cuyuni-Mazaruni" },
  { value: "DE", label: "Demerara-Mahaica" },
  { value: "EB", label: "East Berbice-Corentyne" },
  { value: "ES", label: "Essequibo Islands-West Demerara" },
  { value: "MA", label: "Mahaica-Berbice" },
  { value: "PM", label: "Pomeroon-Supenaam" },
  { value: "PT", label: "Potaro-Siparuni" },
  { value: "UD", label: "Upper Demerara-Berbice" },
  { value: "UT", label: "Upper Takutu-Upper Essequibo" }
];

// Departamentos do Paraguai
const pyStates = [
  { value: "ASU", label: "Asunción" },
  { value: "CON", label: "Concepción" },
  { value: "SAN", label: "San Pedro" },
  { value: "COR", label: "Cordillera" },
  { value: "GUA", label: "Guairá" },
  { value: "CAA", label: "Caaguazú" },
  { value: "CAZ", label: "Caazapá" },
  { value: "ITA", label: "Itapúa" },
  { value: "MIS", label: "Misiones" },
  { value: "PAR", label: "Paraguarí" },
  { value: "ATO", label: "Alto Paraná" },
  { value: "CEN", label: "Central" },
  { value: "ÑEE", label: "Ñeembucú" },
  { value: "AMA", label: "Amambay" },
  { value: "CAN", label: "Canindeyú" },
  { value: "PRE", label: "Presidente Hayes" },
  { value: "BOQ", label: "Boquerón" },
  { value: "APE", label: "Alto Paraguay" }
];

// Departamentos do Peru
const peStates = [
  { value: "AMA", label: "Amazonas" },
  { value: "ANC", label: "Áncash" },
  { value: "APU", label: "Apurímac" },
  { value: "ARE", label: "Arequipa" },
  { value: "AYA", label: "Ayacucho" },
  { value: "CAJ", label: "Cajamarca" },
  { value: "CAL", label: "Callao" },
  { value: "CUS", label: "Cusco" },
  { value: "HUV", label: "Huancavelica" },
  { value: "HUA", label: "Huánuco" },
  { value: "ICA", label: "Ica" },
  { value: "JUN", label: "Junín" },
  { value: "LAL", label: "La Libertad" },
  { value: "LAM", label: "Lambayeque" },
  { value: "LIM", label: "Lima" },
  { value: "LOR", label: "Loreto" },
  { value: "MDD", label: "Madre de Dios" },
  { value: "MOQ", label: "Moquegua" },
  { value: "PAS", label: "Pasco" },
  { value: "PIU", label: "Piura" },
  { value: "PUN", label: "Puno" },
  { value: "SAM", label: "San Martín" },
  { value: "TAC", label: "Tacna" },
  { value: "TUM", label: "Tumbes" },
  { value: "UCA", label: "Ucayali" }
];

// Distritos do Suriname
const srStates = [
  { value: "BR", label: "Brokopondo" },
  { value: "CM", label: "Commewijne" },
  { value: "CR", label: "Coronie" },
  { value: "MA", label: "Marowijne" },
  { value: "NI", label: "Nickerie" },
  { value: "PR", label: "Para" },
  { value: "PM", label: "Paramaribo" },
  { value: "SA", label: "Saramacca" },
  { value: "SI", label: "Sipaliwini" },
  { value: "WA", label: "Wanica" }
];

// Departamentos do Uruguai
const uyStates = [
  { value: "AR", label: "Artigas" },
  { value: "CA", label: "Canelones" },
  { value: "CL", label: "Cerro Largo" },
  { value: "CO", label: "Colonia" },
  { value: "DU", label: "Durazno" },
  { value: "FS", label: "Flores" },
  { value: "FD", label: "Florida" },
  { value: "LA", label: "Lavalleja" },
  { value: "MA", label: "Maldonado" },
  { value: "MO", label: "Montevideo" },
  { value: "PA", label: "Paysandú" },
  { value: "RN", label: "Río Negro" },
  { value: "RV", label: "Rivera" },
  { value: "RO", label: "Rocha" },
  { value: "SA", label: "Salto" },
  { value: "SJ", label: "San José" },
  { value: "SO", label: "Soriano" },
  { value: "TA", label: "Tacuarembó" },
  { value: "TT", label: "Treinta y Tres" }
];

// Estados da Venezuela
const veStates = [
  { value: "AM", label: "Amazonas" },
  { value: "AN", label: "Anzoátegui" },
  { value: "AP", label: "Apure" },
  { value: "AR", label: "Aragua" },
  { value: "BA", label: "Barinas" },
  { value: "BO", label: "Bolívar" },
  { value: "CA", label: "Carabobo" },
  { value: "CO", label: "Cojedes" },
  { value: "DA", label: "Delta Amacuro" },
  { value: "DC", label: "Distrito Capital" },
  { value: "FA", label: "Falcón" },
  { value: "GU", label: "Guárico" },
  { value: "LA", label: "Lara" },
  { value: "ME", label: "Mérida" },
  { value: "MI", label: "Miranda" },
  { value: "MO", label: "Monagas" },
  { value: "NE", label: "Nueva Esparta" },
  { value: "PO", label: "Portuguesa" },
  { value: "SU", label: "Sucre" },
  { value: "TA", label: "Táchira" },
  { value: "TR", label: "Trujillo" },
  { value: "VA", label: "Vargas" },
  { value: "YA", label: "Yaracuy" },
  { value: "ZU", label: "Zulia" }
];

// Províncias/Territórios do Canadá
const caStates = [
  { value: "AB", label: "Alberta" },
  { value: "BC", label: "British Columbia" },
  { value: "MB", label: "Manitoba" },
  { value: "NB", label: "New Brunswick" },
  { value: "NL", label: "Newfoundland and Labrador" },
  { value: "NS", label: "Nova Scotia" },
  { value: "ON", label: "Ontario" },
  { value: "PE", label: "Prince Edward Island" },
  { value: "QC", label: "Quebec" },
  { value: "SK", label: "Saskatchewan" },
  { value: "NT", label: "Northwest Territories" },
  { value: "NU", label: "Nunavut" },
  { value: "YT", label: "Yukon" }
];

// Estados do México
const mxStates = [
  { value: "AG", label: "Aguascalientes" },
  { value: "BC", label: "Baja California" },
  { value: "BS", label: "Baja California Sur" },
  { value: "CM", label: "Campeche" },
  { value: "CS", label: "Chiapas" },
  { value: "CH", label: "Chihuahua" },
  { value: "CX", label: "Ciudad de México" },
  { value: "CO", label: "Coahuila" },
  { value: "CL", label: "Colima" },
  { value: "DG", label: "Durango" },
  { value: "GT", label: "Guanajuato" },
  { value: "GR", label: "Guerrero" },
  { value: "HG", label: "Hidalgo" },
  { value: "JA", label: "Jalisco" },
  { value: "EM", label: "Estado de México" },
  { value: "MI", label: "Michoacán" },
  { value: "MO", label: "Morelos" },
  { value: "NA", label: "Nayarit" },
  { value: "NL", label: "Nuevo León" },
  { value: "OA", label: "Oaxaca" },
  { value: "PU", label: "Puebla" },
  { value: "QT", label: "Querétaro" },
  { value: "QR", label: "Quintana Roo" },
  { value: "SL", label: "San Luis Potosí" },
  { value: "SI", label: "Sinaloa" },
  { value: "SO", label: "Sonora" },
  { value: "TB", label: "Tabasco" },
  { value: "TM", label: "Tamaulipas" },
  { value: "TL", label: "Tlaxcala" },
  { value: "VE", label: "Veracruz" },
  { value: "YU", label: "Yucatán" },
  { value: "ZA", label: "Zacatecas" }
];

// Estados da Alemanha
const deStates = [
  { value: "BW", label: "Baden-Württemberg" },
  { value: "BY", label: "Bayern (Bavaria)" },
  { value: "BE", label: "Berlin" },
  { value: "BB", label: "Brandenburg" },
  { value: "HB", label: "Bremen" },
  { value: "HH", label: "Hamburg" },
  { value: "HE", label: "Hessen" },
  { value: "MV", label: "Mecklenburg-Vorpommern" },
  { value: "NI", label: "Niedersachsen" },
  { value: "NW", label: "Nordrhein-Westfalen" },
  { value: "RP", label: "Rheinland-Pfalz" },
  { value: "SL", label: "Saarland" },
  { value: "SN", label: "Sachsen" },
  { value: "ST", label: "Sachsen-Anhalt" },
  { value: "SH", label: "Schleswig-Holstein" },
  { value: "TH", label: "Thüringen" }
];

// Estados da Áustria
const atStates = [
  { value: "1", label: "Burgenland" },
  { value: "2", label: "Kärnten" },
  { value: "3", label: "Niederösterreich" },
  { value: "4", label: "Oberösterreich" },
  { value: "5", label: "Salzburg" },
  { value: "6", label: "Steiermark" },
  { value: "7", label: "Tirol" },
  { value: "8", label: "Vorarlberg" },
  { value: "9", label: "Wien" }
];

// Regiões da Bélgica
const beStates = [
  { value: "BRU", label: "Brussels-Capital Region" },
  { value: "VLG", label: "Flemish Region" },
  { value: "WAL", label: "Walloon Region" }
];

// Comunidades Autônomas da Espanha
const esStates = [
  { value: "AN", label: "Andalucía" },
  { value: "AR", label: "Aragón" },
  { value: "AS", label: "Asturias" },
  { value: "IB", label: "Islas Baleares" },
  { value: "CN", label: "Canarias" },
  { value: "CB", label: "Cantabria" },
  { value: "CM", label: "Castilla-La Mancha" },
  { value: "CL", label: "Castilla y León" },
  { value: "CT", label: "Cataluña" },
  { value: "EX", label: "Extremadura" },
  { value: "GA", label: "Galicia" },
  { value: "MD", label: "Madrid" },
  { value: "MC", label: "Murcia" },
  { value: "NC", label: "Navarra" },
  { value: "PV", label: "País Vasco" },
  { value: "RI", label: "La Rioja" },
  { value: "VC", label: "Valencia" },
  { value: "CE", label: "Ceuta" },
  { value: "ML", label: "Melilla" }
];

// Regiões da França
const frStates = [
  { value: "ARA", label: "Auvergne-Rhône-Alpes" },
  { value: "BFC", label: "Bourgogne-Franche-Comté" },
  { value: "BRE", label: "Bretagne" },
  { value: "CVL", label: "Centre-Val de Loire" },
  { value: "COR", label: "Corse" },
  { value: "GES", label: "Grand Est" },
  { value: "HDF", label: "Hauts-de-France" },
  { value: "IDF", label: "Île-de-France" },
  { value: "NOR", label: "Normandie" },
  { value: "NAQ", label: "Nouvelle-Aquitaine" },
  { value: "OCC", label: "Occitanie" },
  { value: "PDL", label: "Pays de la Loire" },
  { value: "PAC", label: "Provence-Alpes-Côte d'Azur" }
];

// Regiões da Itália
const itStates = [
  { value: "ABR", label: "Abruzzo" },
  { value: "BAS", label: "Basilicata" },
  { value: "CAL", label: "Calabria" },
  { value: "CAM", label: "Campania" },
  { value: "EMR", label: "Emilia-Romagna" },
  { value: "FVG", label: "Friuli-Venezia Giulia" },
  { value: "LAZ", label: "Lazio" },
  { value: "LIG", label: "Liguria" },
  { value: "LOM", label: "Lombardia" },
  { value: "MAR", label: "Marche" },
  { value: "MOL", label: "Molise" },
  { value: "PIE", label: "Piemonte" },
  { value: "PUG", label: "Puglia" },
  { value: "SAR", label: "Sardegna" },
  { value: "SIC", label: "Sicilia" },
  { value: "TOS", label: "Toscana" },
  { value: "TAA", label: "Trentino-Alto Adige" },
  { value: "UMB", label: "Umbria" },
  { value: "VDA", label: "Valle d'Aosta" },
  { value: "VEN", label: "Veneto" }
];

// Países constituintes do Reino Unido
const gbStates = [
  { value: "ENG", label: "England" },
  { value: "SCT", label: "Scotland" },
  { value: "WLS", label: "Wales" },
  { value: "NIR", label: "Northern Ireland" }
];

// Estados da Índia
const inStates = [
  { value: "AN", label: "Andaman and Nicobar Islands" },
  { value: "AP", label: "Andhra Pradesh" },
  { value: "AR", label: "Arunachal Pradesh" },
  { value: "AS", label: "Assam" },
  { value: "BR", label: "Bihar" },
  { value: "CH", label: "Chandigarh" },
  { value: "CT", label: "Chhattisgarh" },
  { value: "DN", label: "Dadra and Nagar Haveli" },
  { value: "DD", label: "Daman and Diu" },
  { value: "DL", label: "Delhi" },
  { value: "GA", label: "Goa" },
  { value: "GJ", label: "Gujarat" },
  { value: "HR", label: "Haryana" },
  { value: "HP", label: "Himachal Pradesh" },
  { value: "JK", label: "Jammu and Kashmir" },
  { value: "JH", label: "Jharkhand" },
  { value: "KA", label: "Karnataka" },
  { value: "KL", label: "Kerala" },
  { value: "LD", label: "Lakshadweep" },
  { value: "MP", label: "Madhya Pradesh" },
  { value: "MH", label: "Maharashtra" },
  { value: "MN", label: "Manipur" },
  { value: "ML", label: "Meghalaya" },
  { value: "MZ", label: "Mizoram" },
  { value: "NL", label: "Nagaland" },
  { value: "OR", label: "Odisha" },
  { value: "PY", label: "Puducherry" },
  { value: "PB", label: "Punjab" },
  { value: "RJ", label: "Rajasthan" },
  { value: "SK", label: "Sikkim" },
  { value: "TN", label: "Tamil Nadu" },
  { value: "TG", label: "Telangana" },
  { value: "TR", label: "Tripura" },
  { value: "UP", label: "Uttar Pradesh" },
  { value: "UT", label: "Uttarakhand" },
  { value: "WB", label: "West Bengal" }
];

// Províncias da Indonésia
const idStates = [
  { value: "AC", label: "Aceh" },
  { value: "SU", label: "Sumatera Utara" },
  { value: "SB", label: "Sumatera Barat" },
  { value: "RI", label: "Riau" },
  { value: "JA", label: "Jambi" },
  { value: "SS", label: "Sumatera Selatan" },
  { value: "BB", label: "Bangka Belitung" },
  { value: "BE", label: "Bengkulu" },
  { value: "LA", label: "Lampung" },
  { value: "KR", label: "Kepulauan Riau" },
  { value: "JK", label: "DKI Jakarta" },
  { value: "JB", label: "Jawa Barat" },
  { value: "JT", label: "Jawa Tengah" },
  { value: "YO", label: "DI Yogyakarta" },
  { value: "JI", label: "Jawa Timur" },
  { value: "BT", label: "Banten" },
  { value: "BA", label: "Bali" },
  { value: "NB", label: "Nusa Tenggara Barat" },
  { value: "NT", label: "Nusa Tenggara Timur" },
  { value: "KB", label: "Kalimantan Barat" },
  { value: "KT", label: "Kalimantan Tengah" },
  { value: "KS", label: "Kalimantan Selatan" },
  { value: "KI", label: "Kalimantan Timur" },
  { value: "KU", label: "Kalimantan Utara" },
  { value: "SA", label: "Sulawesi Utara" },
  { value: "ST", label: "Sulawesi Tengah" },
  { value: "SN", label: "Sulawesi Selatan" },
  { value: "SG", label: "Sulawesi Tenggara" },
  { value: "GO", label: "Gorontalo" },
  { value: "SR", label: "Sulawesi Barat" },
  { value: "MA", label: "Maluku" },
  { value: "MU", label: "Maluku Utara" },
  { value: "PA", label: "Papua" },
  { value: "PB", label: "Papua Barat" }
];

// Prefeituras do Japão
const jpStates = [
  { value: "01", label: "Hokkaido" },
  { value: "02", label: "Aomori" },
  { value: "03", label: "Iwate" },
  { value: "04", label: "Miyagi" },
  { value: "05", label: "Akita" },
  { value: "06", label: "Yamagata" },
  { value: "07", label: "Fukushima" },
  { value: "08", label: "Ibaraki" },
  { value: "09", label: "Tochigi" },
  { value: "10", label: "Gunma" },
  { value: "11", label: "Saitama" },
  { value: "12", label: "Chiba" },
  { value: "13", label: "Tokyo" },
  { value: "14", label: "Kanagawa" },
  { value: "15", label: "Niigata" },
  { value: "16", label: "Toyama" },
  { value: "17", label: "Ishikawa" },
  { value: "18", label: "Fukui" },
  { value: "19", label: "Yamanashi" },
  { value: "20", label: "Nagano" },
  { value: "21", label: "Gifu" },
  { value: "22", label: "Shizuoka" },
  { value: "23", label: "Aichi" },
  { value: "24", label: "Mie" },
  { value: "25", label: "Shiga" },
  { value: "26", label: "Kyoto" },
  { value: "27", label: "Osaka" },
  { value: "28", label: "Hyogo" },
  { value: "29", label: "Nara" },
  { value: "30", label: "Wakayama" },
  { value: "31", label: "Tottori" },
  { value: "32", label: "Shimane" },
  { value: "33", label: "Okayama" },
  { value: "34", label: "Hiroshima" },
  { value: "35", label: "Yamaguchi" },
  { value: "36", label: "Tokushima" },
  { value: "37", label: "Kagawa" },
  { value: "38", label: "Ehime" },
  { value: "39", label: "Kochi" },
  { value: "40", label: "Fukuoka" },
  { value: "41", label: "Saga" },
  { value: "42", label: "Nagasaki" },
  { value: "43", label: "Kumamoto" },
  { value: "44", label: "Oita" },
  { value: "45", label: "Miyazaki" },
  { value: "46", label: "Kagoshima" },
  { value: "47", label: "Okinawa" }
];

// Estados da Malásia
const myStates = [
  { value: "JH", label: "Johor" },
  { value: "KD", label: "Kedah" },
  { value: "KL", label: "Kelantan" },
  { value: "ML", label: "Melaka" },
  { value: "NS", label: "Negeri Sembilan" },
  { value: "PA", label: "Pahang" },
  { value: "PK", label: "Perak" },
  { value: "PR", label: "Perlis" },
  { value: "PP", label: "Pulau Pinang" },
  { value: "SB", label: "Sabah" },
  { value: "SW", label: "Sarawak" },
  { value: "SL", label: "Selangor" },
  { value: "TR", label: "Terengganu" },
  { value: "KU", label: "Kuala Lumpur" },
  { value: "LB", label: "Labuan" },
  { value: "PJ", label: "Putrajaya" }
];

// Províncias da Tailândia
const thStates = [
  { value: "10", label: "Bangkok" },
  { value: "11", label: "Samut Prakan" },
  { value: "12", label: "Nonthaburi" },
  { value: "13", label: "Pathum Thani" },
  { value: "14", label: "Phra Nakhon Si Ayutthaya" },
  { value: "15", label: "Ang Thong" },
  { value: "16", label: "Lopburi" },
  { value: "17", label: "Sing Buri" },
  { value: "18", label: "Chai Nat" },
  { value: "19", label: "Saraburi" },
  { value: "20", label: "Chonburi" },
  { value: "21", label: "Rayong" },
  { value: "22", label: "Chanthaburi" },
  { value: "23", label: "Trat" },
  { value: "24", label: "Chachoengsao" },
  { value: "25", label: "Prachinburi" },
  { value: "26", label: "Nakhon Nayok" },
  { value: "27", label: "Sa Kaeo" },
  { value: "30", label: "Nakhon Ratchasima" },
  { value: "31", label: "Buriram" },
  { value: "32", label: "Surin" },
  { value: "33", label: "Sisaket" },
  { value: "34", label: "Ubon Ratchathani" },
  { value: "35", label: "Yasothon" },
  { value: "36", label: "Chaiyaphum" },
  { value: "37", label: "Amnat Charoen" },
  { value: "39", label: "Nong Bua Lamphu" },
  { value: "40", label: "Khon Kaen" },
  { value: "41", label: "Udon Thani" },
  { value: "42", label: "Loei" },
  { value: "43", label: "Nong Khai" },
  { value: "44", label: "Maha Sarakham" },
  { value: "45", label: "Roi Et" },
  { value: "46", label: "Kalasin" },
  { value: "47", label: "Sakon Nakhon" },
  { value: "48", label: "Nakhon Phanom" },
  { value: "49", label: "Mukdahan" },
  { value: "50", label: "Chiang Mai" },
  { value: "51", label: "Lamphun" },
  { value: "52", label: "Lampang" },
  { value: "53", label: "Uttaradit" },
  { value: "54", label: "Phrae" },
  { value: "55", label: "Nan" },
  { value: "56", label: "Phayao" },
  { value: "57", label: "Chiang Rai" },
  { value: "58", label: "Mae Hong Son" },
  { value: "60", label: "Nakhon Sawan" },
  { value: "61", label: "Uthai Thani" },
  { value: "62", label: "Kamphaeng Phet" },
  { value: "63", label: "Tak" },
  { value: "64", label: "Sukhothai" },
  { value: "65", label: "Phitsanulok" },
  { value: "66", label: "Phichit" },
  { value: "67", label: "Phetchabun" },
  { value: "70", label: "Ratchaburi" },
  { value: "71", label: "Kanchanaburi" },
  { value: "72", label: "Suphanburi" },
  { value: "73", label: "Nakhon Pathom" },
  { value: "74", label: "Samut Sakhon" },
  { value: "75", label: "Samut Songkhram" },
  { value: "76", label: "Phetchaburi" },
  { value: "77", label: "Prachuap Khiri Khan" },
  { value: "80", label: "Nakhon Si Thammarat" },
  { value: "81", label: "Krabi" },
  { value: "82", label: "Phangnga" },
  { value: "83", label: "Phuket" },
  { value: "84", label: "Surat Thani" },
  { value: "85", label: "Ranong" },
  { value: "86", label: "Chumphon" },
  { value: "90", label: "Songkhla" },
  { value: "91", label: "Satun" },
  { value: "92", label: "Trang" },
  { value: "93", label: "Phatthalung" },
  { value: "94", label: "Pattani" },
  { value: "95", label: "Yala" },
  { value: "96", label: "Narathiwat" },
  { value: "S", label: "Bueng Kan" }
];

// Províncias da Turquia
const trStates = [
  { value: "01", label: "Adana" },
  { value: "02", label: "Adıyaman" },
  { value: "03", label: "Afyonkarahisar" },
  { value: "04", label: "Ağrı" },
  { value: "05", label: "Amasya" },
  { value: "06", label: "Ankara" },
  { value: "07", label: "Antalya" },
  { value: "08", label: "Artvin" },
  { value: "09", label: "Aydın" },
  { value: "10", label: "Balıkesir" },
  { value: "11", label: "Bilecik" },
  { value: "12", label: "Bingöl" },
  { value: "13", label: "Bitlis" },
  { value: "14", label: "Bolu" },
  { value: "15", label: "Burdur" },
  { value: "16", label: "Bursa" },
  { value: "17", label: "Çanakkale" },
  { value: "18", label: "Çankırı" },
  { value: "19", label: "Çorum" },
  { value: "20", label: "Denizli" },
  { value: "21", label: "Diyarbakır" },
  { value: "22", label: "Edirne" },
  { value: "23", label: "Elazığ" },
  { value: "24", label: "Erzincan" },
  { value: "25", label: "Erzurum" },
  { value: "26", label: "Eskişehir" },
  { value: "27", label: "Gaziantep" },
  { value: "28", label: "Giresun" },
  { value: "29", label: "Gümüşhane" },
  { value: "30", label: "Hakkâri" },
  { value: "31", label: "Hatay" },
  { value: "32", label: "Isparta" },
  { value: "33", label: "Mersin" },
  { value: "34", label: "İstanbul" },
  { value: "35", label: "İzmir" },
  { value: "36", label: "Kars" },
  { value: "37", label: "Kastamonu" },
  { value: "38", label: "Kayseri" },
  { value: "39", label: "Kırklareli" },
  { value: "40", label: "Kırşehir" },
  { value: "41", label: "Kocaeli" },
  { value: "42", label: "Konya" },
  { value: "43", label: "Kütahya" },
  { value: "44", label: "Malatya" },
  { value: "45", label: "Manisa" },
  { value: "46", label: "Kahramanmaraş" },
  { value: "47", label: "Mardin" },
  { value: "48", label: "Muğla" },
  { value: "49", label: "Muş" },
  { value: "50", label: "Nevşehir" },
  { value: "51", label: "Niğde" },
  { value: "52", label: "Ordu" },
  { value: "53", label: "Rize" },
  { value: "54", label: "Sakarya" },
  { value: "55", label: "Samsun" },
  { value: "56", label: "Siirt" },
  { value: "57", label: "Sinop" },
  { value: "58", label: "Sivas" },
  { value: "59", label: "Tekirdağ" },
  { value: "60", label: "Tokat" },
  { value: "61", label: "Trabzon" },
  { value: "62", label: "Tunceli" },
  { value: "63", label: "Şanlıurfa" },
  { value: "64", label: "Uşak" },
  { value: "65", label: "Van" },
  { value: "66", label: "Yozgat" },
  { value: "67", label: "Zonguldak" },
  { value: "68", label: "Aksaray" },
  { value: "69", label: "Bayburt" },
  { value: "70", label: "Karaman" },
  { value: "71", label: "Kırıkkale" },
  { value: "72", label: "Batman" },
  { value: "73", label: "Şırnak" },
  { value: "74", label: "Bartın" },
  { value: "75", label: "Ardahan" },
  { value: "76", label: "Iğdır" },
  { value: "77", label: "Yalova" },
  { value: "78", label: "Karabük" },
  { value: "79", label: "Kilis" },
  { value: "80", label: "Osmaniye" },
  { value: "81", label: "Düzce" }
];

// Estados/Territórios da Austrália
const auStates = [
  { value: "NSW", label: "New South Wales" },
  { value: "QLD", label: "Queensland" },
  { value: "SA", label: "South Australia" },
  { value: "TAS", label: "Tasmania" },
  { value: "VIC", label: "Victoria" },
  { value: "WA", label: "Western Australia" },
  { value: "ACT", label: "Australian Capital Territory" },
  { value: "NT", label: "Northern Territory" }
];

// Regiões da Nova Zelândia
const nzStates = [
  { value: "AUK", label: "Auckland" },
  { value: "BOP", label: "Bay of Plenty" },
  { value: "CAN", label: "Canterbury" },
  { value: "GIS", label: "Gisborne" },
  { value: "HKB", label: "Hawke's Bay" },
  { value: "MWT", label: "Manawatū-Whanganui" },
  { value: "MBH", label: "Marlborough" },
  { value: "NSN", label: "Nelson" },
  { value: "NTL", label: "Northland" },
  { value: "OTA", label: "Otago" },
  { value: "STL", label: "Southland" },
  { value: "TKI", label: "Taranaki" },
  { value: "TAS", label: "Tasman" },
  { value: "WKO", label: "Waikato" },
  { value: "WGN", label: "Wellington" },
  { value: "WTC", label: "West Coast" }
];

// Províncias da África do Sul
const zaStates = [
  { value: "EC", label: "Eastern Cape" },
  { value: "FS", label: "Free State" },
  { value: "GP", label: "Gauteng" },
  { value: "KZN", label: "KwaZulu-Natal" },
  { value: "LP", label: "Limpopo" },
  { value: "MP", label: "Mpumalanga" },
  { value: "NC", label: "Northern Cape" },
  { value: "NW", label: "North West" },
  { value: "WC", label: "Western Cape" }
];

export const CountryStates: Record<string, { value: string; label: string }[]> = {
  BR: brazilStates,
  US: usStates,
  AR: arStates,
  BO: boStates,
  CL: [{ value: '', label: 'N/A' }],
  CO: coStates,
  EC: [{ value: '', label: 'N/A' }],
  GY: [{ value: '', label: 'N/A' }],
  PY: pyStates,
  PE: peStates,
  SR: [{ value: '', label: 'N/A' }],
  UY: [{ value: '', label: 'N/A' }],
  VE: veStates,
  CA: caStates,
  MX: mxStates,
  CR: [{ value: '', label: 'N/A' }],
  CU: [{ value: '', label: 'N/A' }],
  SV: [{ value: '', label: 'N/A' }],
  GT: [{ value: '', label: 'N/A' }],
  HT: [{ value: '', label: 'N/A' }],
  HN: [{ value: '', label: 'N/A' }],
  NI: [{ value: '', label: 'N/A' }],
  PA: [{ value: '', label: 'N/A' }],
  DO: [{ value: '', label: 'N/A' }],
  DE: deStates,
  AT: atStates,
  BE: beStates,
  BG: [{ value: '', label: 'N/A' }],
  DK: [{ value: '', label: 'N/A' }],
  SK: [{ value: '', label: 'N/A' }],
  SI: [{ value: '', label: 'N/A' }],
  ES: esStates,
  FI: [{ value: '', label: 'N/A' }],
  FR: frStates,
  GR: [{ value: '', label: 'N/A' }],
  HU: [{ value: '', label: 'N/A' }],
  IE: [{ value: '', label: 'N/A' }],
  IT: itStates,
  LU: [{ value: '', label: 'N/A' }],
  NO: [{ value: '', label: 'N/A' }],
  NL: [{ value: '', label: 'N/A' }],
  PL: [{ value: '', label: 'N/A' }],
  PT: [{ value: '', label: 'N/A' }],
  GB: [{ value: '', label: 'N/A' }],
  CZ: [{ value: '', label: 'N/A' }],
  RO: [{ value: '', label: 'N/A' }],
  SE: [{ value: '', label: 'N/A' }],
  CH: [{ value: '', label: 'N/A' }],
  CN: [{ value: '', label: 'N/A' }],
  KR: [{ value: '', label: 'N/A' }],
  AE: [{ value: '', label: 'N/A' }],
  HK: [{ value: '', label: 'N/A' }],
  IN: [{ value: '', label: 'N/A' }],
  ID: [{ value: '', label: 'N/A' }],
  IL: [{ value: '', label: 'N/A' }],
  JP: [{ value: '', label: 'N/A' }],
  MY: [{ value: '', label: 'N/A' }],
  SG: [{ value: '', label: 'N/A' }],
  TH: [{ value: '', label: 'N/A' }],
  TR: trStates,
  VN: [{ value: '', label: 'N/A' }],
  AU: auStates,
  NZ: nzStates,
  ZA: zaStates,
  AO: [{ value: '', label: 'N/A' }],
  CM: [{ value: '', label: 'N/A' }],
  EG: [{ value: '', label: 'N/A' }],
  ET: [{ value: '', label: 'N/A' }],
  GH: [{ value: '', label: 'N/A' }],
  KE: [{ value: '', label: 'N/A' }],
  MA: [{ value: '', label: 'N/A' }],
  MZ: [{ value: '', label: 'N/A' }],
  NG: [{ value: '', label: 'N/A' }],
  SN: [{ value: '', label: 'N/A' }],
  TN: [{ value: '', label: 'N/A' }]
}; 